from pathlib import Path
import re

p = Path('main.tex')
t = p.read_text()


def between(start, end, name):
    i = t.find(start)
    if i < 0:
        raise SystemExit(f'{name}: start marker not found')
    j = t.find(end, i + len(start))
    if j < 0:
        raise SystemExit(f'{name}: end marker not found')
    return i, j, t[i:j]


def pop_between(start, end, name):
    global t
    i, j, block = between(start, end, name)
    t = t[:i] + t[j:]
    return block.strip() + '\n\n'

# -----------------------------------------------------------------------------
# 1. Remove the process-specific examples from Sec. 6. They will be reinserted
#    in full in the NNLO-observable section, together with their integrated
#    consequences, so that neither example is split across the note.
# -----------------------------------------------------------------------------

dy_local = pop_between(
    r'\subsubsection{Drell--Yan illustration}\n',
    r'\subsubsection{\texorpdfstring{$Z+1$-jet}{Z+1-jet} illustration}\n',
    'DY local example'
)

z_local = pop_between(
    r'\subsubsection{\texorpdfstring{$Z+1$-jet}{Z+1-jet} illustration}\n',
    r'\section{Differential locality of the lower map}\n',
    'Z+1jet local example'
)

# Move the explicit process specializations of the minimized-jettiness bound as
# well. The generic bound remains in Sec. 6.
proc_bounds_start = r'For Drell--Yan double-real kinematics, the relevant configuration is '
proc_bounds_end = r'\subsection{Observable response to projection-induced migrations}\n'
i, j, proc_bounds = between(proc_bounds_start, proc_bounds_end, 'process-specific jettiness bounds')
t = t[:i] + t[j:]
proc_bounds = proc_bounds.strip() + '\n\n'

# Split the short process-bound block into DY and Z+1j pieces.
needle = r'For a three-parton configuration, relevant for the next multiplicity in the colour-singlet-plus-jet NNLO\n'
k = proc_bounds.find(needle)
if k < 0:
    raise SystemExit('could not split DY and Z+1jet jettiness specializations')
dy_bound = proc_bounds[:k].strip() + '\n\n'
z_bound = proc_bounds[k:].strip() + '\n\n'

# -----------------------------------------------------------------------------
# 2. Replace old Sections 7--10 by one coherent section. The notation is kept
#    in terms of r_{N-1}, r_N, r_{N+1} throughout.
# -----------------------------------------------------------------------------

old7_start = r'\section{Differential locality of the lower map}\n'
old11_start = r'\section{From local projection effects to NNLO differential predictions}\n'
i, j, _ = between(old7_start, old11_start, 'old Sections 7--10')

new7 = r'''\section{Lower-map locality and nested consistency before NNLO observables}
\label{sec:lower-map-locality}

Section~\ref{sec:higher-singular-spectrum} analyzed a very specific object: the modification induced by the
higher projection $\Pi_{N+1}$ on the singular spectrum that is still differential in the lower resolution
variable $\rn$.  It would be premature to integrate that spectrum over $\rn$ and interpret the result as the
projection effect on an NNLO observable.  The reason is that an NNLO event definition contains two adjacent
$\rn$ regions.  For $\rn>\rn^{\cut}$ the calculation is the NLO $(N+1)$-parton contribution discussed above,
including the possible $\Ph_{N+2}\to\widehat\Ph_{N+1}$ LHE replacement.  For
$\rn<\rn^{\cut}$, however, the event is represented on $N$-parton kinematics and the unresolved
$(N+1)$-parton configurations are related to that representation by the lower map
\begin{equation}
\Pi_N:\Ph_{N+1}\longrightarrow\widehat\Ph_N.
\label{eq:lower-map}
\end{equation}
Before adding the two regions and integrating over $\rn$, one must therefore establish that this second
projection is local in the variables on which the lower-multiplicity singular prediction depends.  Otherwise
one could attribute to the higher $\rnp^{\cut}$ projection an effect that actually originates in the
representation of the lower $\rn<\rn^{\cut}$ bin.

This section is therefore a necessary intermediate step rather than a digression into a different problem.
It repeats one rung lower the logic developed for $\Pi_{N+1}$ in Sec.~\ref{sec:higher-singular-spectrum}:
$\rnp$ is replaced by $\rn$, the singular spectrum in $\rn$ is replaced by the next lower spectrum in
$\rnm$, and the relevant projection becomes $\Pi_N$.  The discussion also separates differential locality
from migration across an optional process-defining boundary in $\rnm$.  Only after these lower-map properties
have been made explicit will Sec.~\ref{sec:nnlo-differential-predictions} integrate over $\rn$ and discuss
physical NNLO observables.

\subsection{Differential locality of \texorpdfstring{$\Pi_N$}{PiN} in \texorpdfstring{$r_{N-1}$}{rN-1}}
\label{subsec:lower-map-differential-locality}

Let $\rnm^{(N+1)}(\Ph_{N+1})$ denote the extension of the lower resolution variable to the
$(N+1)$-parton configuration and define the displacement generated by the lower projection with the same
exact-minus-projected convention used above,
\begin{equation}
\Delta\rnm(\Ph_{N+1})
\equiv
\rnm^{(N+1)}(\Ph_{N+1})
-
\rnm\!\left(\Pi_N(\Ph_{N+1})\right).
\label{eq:delta-rnm}
\end{equation}
If the $N$-parton singular prediction is kept differential in $\rnm$, locality requires the exact and
projected configurations to approach the same value of this coordinate as the extra emission becomes
unresolved.  Introducing a finite nonsingular characteristic scale $r_{N-1,\rm char}$, a minimal condition is
\begin{equation}
\frac{\Delta\rnm}{r_{N-1,\rm char}}
\longrightarrow0
\qquad
\text{for }\rn/Q\to0
\text{ at fixed lower-multiplicity kinematics}.
\label{eq:lower-map-locality-condition}
\end{equation}
Exact preservation,
\begin{equation}
\rnm\!\left(\Pi_N(\Ph_{N+1})\right)
=
\rnm^{(N+1)}(\Ph_{N+1}),
\label{eq:exact-lower-preservation}
\end{equation}
is sufficient but is stronger than necessary.  What matters for the leading-power construction is that the
mismatch vanish with a positive power, or otherwise sufficiently rapidly, in the unresolved limit.

There is a second nested limit when $\rnm$ itself becomes small.  In a strongly ordered region
\begin{equation}
\rn\ll\rnm\ll Q,
\label{eq:lower-strong-ordering}
\end{equation}
a possible power-like behavior is
\begin{equation}
\frac{\Delta\rnm}{r_{N-1,\rm char}}
\sim
c(\mathbf X,\Ph_{\rm rad})
\left(\frac{\rn}{\rnm}\right)^p,
\qquad p>0.
\label{eq:lower-map-strong-scaling}
\end{equation}
As in Sec.~\ref{subsec:uniform-nested-locality}, this expression is meaningful only in the ordered regime.
If $\rn/\rnm$ remains finite while both variables vanish, the appropriate requirement is the one-rung-lower
analogue of uniform nested infrared locality: the exact $(N+1)$-parton state and its projected $N$-parton
representative must approach the same underlying $(N-1)$-body point for finite kinematically allowed values
of $\rn/\rnm$.  This condition concerns the differential structure of the lower singular prediction and is
present whether or not a cut on $\rnm$ is imposed.

\subsection{Migration of the singular \texorpdfstring{$r_{N-1}$}{rN-1} spectrum}
\label{sec:lower-map-toy}

The consequence of a nonzero $\Delta\rnm$ can be derived directly, without introducing a separate toy
variable.  Schematically, the singular $(N+1)$-parton contribution in the lower unresolved region has the
form
\begin{equation}
\frac{d\sigma_{N+1}^{\rm sing}}
{d\rn\,d\rnm}
\sim
\frac{1}{\rn}
F\!\left(\rnm,\mathbf X,
\ln\frac{\rn}{Q},\ldots\right),
\label{eq:lower-singular-spectrum}
\end{equation}
where $F$ may itself become singular as $\rnm\to0$.  The projected and exact measurements of $\rnm$ differ by
\begin{align}
&\delta\!\left(
\rnm^{\rm obs}-\rnm\!\left(\Pi_N(\Ph_{N+1})\right)
\right)
-
\delta\!\left(
\rnm^{\rm obs}-\rnm^{(N+1)}(\Ph_{N+1})
\right)
\nonumber\\
&\hspace{1cm}\simeq
\Delta\rnm\,
\partial_{\rnm^{\rm obs}}
\delta\!\left(
\rnm^{\rm obs}-\rnm^{(N+1)}(\Ph_{N+1})
\right),
\label{eq:lower-delta-expansion}
\end{align}
where Eq.~\eqref{eq:delta-rnm} fixes the sign convention.  After integrating the unresolved region
$0<\rn<\rn^{\cut}$, the map-dependent contribution therefore has the generic derivative form
\begin{equation}
\Delta_{\Pi_N}
\frac{d\sigma}{d\rnm}
\sim
\partial_{\rnm}
\int_0^{\rn^{\cut}}
\frac{d\rn}{\rn}
\left[
F(\rnm,\ldots)\,\Delta\rnm
\right].
\label{eq:lower-map-migration-master}
\end{equation}
This is the direct lower-level counterpart of the migration derivative in
Eq.~\eqref{eq:rnp-contamination-rn}.  A projection mismatch that is power suppressed in the unresolved
emission can still multiply a spectrum that is singular in the next lower resolution variable.

For the strongly ordered scaling in Eq.~\eqref{eq:lower-map-strong-scaling}, suppressing logarithmic
reshuffling and finite coefficients gives
\begin{equation}
\Delta_{\Pi_N}
\frac{d\sigma}{d\rnm}
\sim
\frac{1}{p}
\left(\frac{\rn^{\cut}}{\rnm}\right)^p
\partial_{\rnm}
\left[
r_{N-1,\rm char}\,\widetilde F(\rnm,\mathbf X)
\right].
\label{eq:lower-map-integrated-scaling}
\end{equation}
Thus the correction vanishes at fixed nonzero $\rnm$ as $\rn^{\cut}\to0$, but the convergence can be
nonuniform when $\rnm$ is simultaneously small.  If the lower spectrum behaves as $F\sim1/\rnm$ and the
map displacement is naturally measured relative to $\rnm$, the relative correction inherits the familiar
neighboring-scale behavior $(\rn^{\cut}/\rnm)^p$ in the ordered region.  This estimate must again not be
extrapolated to $\rn\sim\rnm$; there one needs the simultaneous-limit locality of the lower map.

A map for which $\Delta\rnm$ approaches a nonzero fraction of a lower-multiplicity scale at fixed $\rnm$ as
$\rn\to0$ is not infrared local in this differential variable and can leave logarithmic sensitivity to the
lower technical cut.  Conversely, a displacement that vanishes with a positive but small power of
$\rn/Q$ is formally local but can converge slowly.  This distinction is exactly analogous to the distinction
between failure of uniform nested locality and a large finite-cut coefficient for the higher map.

\subsection{Optional lower generation or fiducial boundaries}
\label{sec:born-boundaries}

The differential-locality issue above exists even when the full range of $\rnm$ is retained.  A separate
condition arises only if the process definition contains an actual lower boundary, for example
\begin{equation}
\ThetaB(\Ph_M)
=
\Theta\!\left(
\rnm^{(M)}(\Ph_M)-\rnm^{\cut}
\right).
\label{eq:active-born-boundary}
\end{equation}
Then exact and projected $(N+1)$-parton configurations can be classified differently by the lower map.  The
relevant difference is
\begin{equation}
\Delta\Theta_B
=
\Theta\!\left(
\rnm\!\left(\Pi_N(\Ph_{N+1})\right)-\rnm^{\cut}
\right)
-
\Theta\!\left(
\rnm^{(N+1)}(\Ph_{N+1})-\rnm^{\cut}
\right),
\label{eq:delta-thetaB}
\end{equation}
and for a small displacement defined in Eq.~\eqref{eq:delta-rnm},
\begin{equation}
\Delta\Theta_B
\simeq
-\Delta\rnm\,
\delta\!\left(
\rnm^{(N+1)}(\Ph_{N+1})-\rnm^{\cut}
\right).
\label{eq:boundary-expansion}
\end{equation}
The resulting correction is localized on the process-defining boundary.  Exact preservation of $\rnm$ removes
it identically; more generally it is sufficient that the exact and projected configurations remain on the
same side of the boundary throughout the singular region.  If no lower generation or fiducial cut is present,
this boundary term is absent, even though the differential-locality condition of the previous subsections
still applies.  If the underlying lower-multiplicity spectrum is itself enhanced near $\rnm=0$, the event
density at an active boundary can make the corresponding classification migration numerically important.

\subsection{Consistency of the two nested projections}
\label{sec:nested-event-consistency}

The two maps now have distinct but complementary responsibilities.  The higher map
\begin{equation}
\Pi_{N+1}:\Ph_{N+2}\to\widehat\Ph_{N+1}
\end{equation}
must be ordinary one-step IR local in the $\rnp\to0$ limit and, for an LHE event definition, uniformly
nested-local as the projected $(N+1)$-parton state also approaches $\rn\to0$.  It should in addition preserve
the already active $\rn$ event classification,
\begin{equation}
\Theta\!\left(
\rn(\widehat\Ph_{N+1})-\rn^{\cut}
\right)
=
\Theta\!\left(
\rn(\Ph_{N+2})-\rn^{\cut}
\right),
\label{eq:rn-boundary-preservation-higher-map}
\end{equation}
with exact preservation of $\rn$ being the simplest sufficient realization.

The lower map $\Pi_N$ must instead be local in every coordinate in which the $N$-parton singular prediction
is retained differential, in particular $\rnm$ when applicable, and it must preserve the classification of
any active lower process-defining boundary.  In the simultaneous $\rnp,\rn\to0$ limit these requirements must
also be mutually compatible.  Denoting by $\Ph_N^{\rm lim}$ the underlying $N$-body point approached by the
exact $\Ph_{N+2}$ configuration, one requires for any smooth coordinate $Y_a$ on the relevant $N$-body
manifold
\begin{equation}
Y_a\!\left(
\Pi_N\!\left(\Pi_{N+1}(\Ph_{N+2})\right)
\right)
-
Y_a(\Ph_N^{\rm lim})
\longrightarrow0
\label{eq:composed-map-consistency}
\end{equation}
as the common unresolved scale is taken to zero along finite kinematically allowed values of
$\rnp/\rn$.  This is not a demand that every intermediate resolution variable be exactly preserved.  It is
a statement that the successive physical event representations approach the same lower-multiplicity
kinematics and respect the boundaries that define the event samples.

The distinction from a pure fixed-order subtraction map remains important.  An auxiliary map can violate
some of these stronger event-level properties while still giving an exact fixed-order result if its dependence
cancels between local and integrated subtraction terms.  Once a projected configuration is retained as an
LHE event, however, there is no compensating measurement on the discarded exact kinematics.  The locality
and boundary conditions discussed here then become properties of the physical event definition itself.

We have now analyzed both locality layers required by the nested construction: the effect of $\Pi_{N+1}$ on
the singular $\rn$ spectrum and the consistency of $\Pi_N$ with the lower $\rnm$ structure.  We can therefore
turn to the quantity of phenomenological interest and integrate over $\rn$ to construct distributions
that are differential only in the physical observables $\mathbf X$.

'''

t = t[:i] + new7 + t[j:]

# -----------------------------------------------------------------------------
# 3. Rebuild the NNLO-observable section so the DY and Z+1j discussions are each
#    self-contained. Keep the generic integrated arguments, then insert the full
#    process examples once.
# -----------------------------------------------------------------------------

# Extract current integrated DY and Z blocks.
dy_cons = pop_between(
    r'\subsubsection{Drell--Yan consequence}\n',
    r'\subsubsection{\texorpdfstring{$Z+1$-jet}{Z+1-jet} consequence}\n',
    'DY integrated consequence'
)

z_cons = pop_between(
    r'\subsubsection{\texorpdfstring{$Z+1$-jet}{Z+1-jet} consequence}\n',
    r'\subsection{Lower \texorpdfstring{$N+1\to N$}{N+1 to N} projection, NNLO power corrections, and P2B}\n',
    'Z+1jet integrated consequence'
)

# Remove cross-references that only existed because the examples were split.
dy_cons = re.sub(
    r'The local Drell--Yan analysis in Sec\.~\\ref\{subsubsec:dy-illustration\} can now be integrated over\n\$\\mathcal T_0\$\.  In the saturated region,\n\n',
    '', dy_cons, count=1
)
z_cons = re.sub(
    r'The local map and jet-response diagnostics were discussed in Sec\.~\\ref\{subsubsec:z1jet-illustration\}\.\n',
    '', z_cons, count=1
)

# Insert the complete examples immediately before the lower-projection/P2B subsection.
insert_marker = r'\subsection{Lower \texorpdfstring{$N+1\to N$}{N+1 to N} projection, NNLO power corrections, and P2B}\n'
idx = t.find(insert_marker)
if idx < 0:
    raise SystemExit('NNLO lower-projection insertion marker not found')

# Add process-specific jettiness bounds at the natural point in each example.
dy_complete = dy_local.replace(
    r'\label{subsubsec:dy-illustration}\n',
    r'\label{subsubsec:dy-illustration}\n\n' + dy_bound,
    1
)
dy_complete = dy_complete.rstrip() + '\n\n' + dy_cons.strip() + '\n\n'

z_complete = z_local.replace(
    r'\label{subsubsec:z1jet-illustration}\n',
    r'\label{subsubsec:z1jet-illustration}\n\n' + z_bound,
    1
)
z_complete = z_complete.rstrip() + '\n\n' + z_cons.strip() + '\n\n'

process_block = (
    r'\subsection{Complete process examples}\n\n'
    + dy_complete
    + z_complete
)
t = t[:idx] + process_block + t[idx:]

# The generic observable-response subsection in Sec. 6 should end without process examples.
# Add a concise bridge if it is not already present.
bridge_marker = r'''when $|\Delta X_i|\ll L_i$. In a smooth region \(L_i\) is of the order of a hard or characteristic
kinematic scale, so uniform nested infrared locality of the map together with IRC safety of the observable
translates into a small projection effect. Near a kinematic boundary, Jacobian feature or Sudakov shoulder,
however, \(L_i\) can become parametrically much smaller than the hard scale. A displacement that is small in
absolute terms can then generate a large local change in the distribution. When \(|\Delta X_i|\) becomes
comparable to the distance from the nonanalytic point, the derivative expansion itself is no longer uniform
and the effect is better viewed as migration across the feature rather than as a small derivative correction.
'''
if bridge_marker not in t:
    raise SystemExit('generic observable-response bridge not found')
t = t.replace(
    bridge_marker,
    bridge_marker + r'''
The statements in this subsection concern the spectrum at fixed $\rn$.  Concrete process examples are
postponed to Sec.~\ref{sec:nnlo-differential-predictions}, where the $\rn$ integration and the complete NNLO
measurement can be discussed at the same time rather than splitting each example between local and integrated
arguments.
''',
    1
)

# Update the NNLO-section introduction: Sec. 7 is now a single intermediate locality section.
t = t.replace(
    r'''Sections~\ref{sec:higher-singular-spectrum}--\ref{sec:nested-event-consistency} characterized the local
singular structure and the locality requirements of the nested maps.  We now perform the logically separate
step of integrating over the lower resolution variable.''',
    r'''Sections~\ref{sec:higher-singular-spectrum} and \ref{sec:lower-map-locality} have now established the
local structure of both projections before any final integration over $\rn$.  We now perform the logically
separate step of constructing NNLO distributions differential only in the physical observables, integrating
the resolved spectrum over the lower resolution variable and combining it with the lower-multiplicity bin.''',
    1
)

# Remove obsolete labels/wording references from the summary and align it with the new organization.
t = t.replace(
    r'''The local strong-ordering expansion of Sec.~\ref{subsec:strongly-ordered-higher-projection} and its
integrated consequence in Sec.~\ref{subsec:higher-projection-nnlo} require a genuine hierarchy.''',
    r'''The local strong-ordering expansion of Sec.~\ref{subsec:strongly-ordered-higher-projection} and its
integrated consequence in Sec.~\ref{subsec:higher-projection-nnlo} require a genuine hierarchy.''',
    1
)

# Structural checks.
for forbidden in [
    r'\section{Toy model for migration',
    r'\section{Optional Born-level fiducial or generation boundaries}',
    r'\section{Consistency conditions for the nested event definition}',
]:
    if forbidden in t:
        raise SystemExit('obsolete standalone section survived: ' + forbidden)

if t.count(r'\subsubsection{Drell--Yan illustration}') != 1:
    raise SystemExit('DY example missing or duplicated')
if t.count(r'\subsubsection{\texorpdfstring{$Z+1$-jet}{Z+1-jet} illustration}') != 1:
    raise SystemExit('Z+1jet example missing or duplicated')
if t.find(r'\subsubsection{Drell--Yan illustration}') < t.find(r'\section{From local projection effects to NNLO differential predictions}'):
    raise SystemExit('DY example still appears before NNLO section')
if t.find(r'\subsubsection{\texorpdfstring{$Z+1$-jet}{Z+1-jet} illustration}') < t.find(r'\section{From local projection effects to NNLO differential predictions}'):
    raise SystemExit('Z+1jet example still appears before NNLO section')

labels = re.findall(r'\\label\{([^}]+)\}', t)
dups = sorted({x for x in labels if labels.count(x) > 1})
if dups:
    raise SystemExit('duplicate labels after restructuring: ' + ', '.join(dups))

p.write_text(t)
